# Generated by Django 2.2.12 on 2020-06-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20200616_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresource',
            old_name='url',
            new_name='access_key',
        ),
    ]
